name: My First Workflow

on: push

jobs:
     first_job:
         runs-on: ubuntu-latest
         steps:
         - name: Welcome message
           run: echo "My first github Actions"

         - name: Checkout
           uses: actions/checkout@v4
         
         - name: List Files
           run: ls -ltr
           
        #  - name: Read File
        #    run: cat README.md 
         
         - name: Print present working directory
           run: pwd
