name: Generate ASCII artwork

on: push

jobs:
     ascii_job:
         runs-on: ubuntu-latest
         steps:

         - name: Checkout
           uses: actions/checkout@v4 

         - name: Install cowsay
           run: sudo apt-get install cowsay -y

         - name: execute cowsay cmd
           run: cowsay -f dragon "Run for cover.....RAWR" >> dragon.txt 

         - name: Test file exists
           run: grep -i "dragon" dragon.txt 

         - name: Read file
           run: cat dragon.txt
         
         - name: checkout repo files
           run: ls -ltra
         
         
        #  - name: List Files
        #    run: ls -ltr
           
        #  - name: Read File
        #    run: cat README.md 
         
        #  - name: Print present working directory
        #    run: pwd
