name: Hello World

on: workflow_dispatch

jobs:
     hello-job:
         runs-on: ubuntu-latest
         steps:
         - name: Echo text
           run: echo "Hello, world!"

         - name: Print pwd
           run: pwd