name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
     strategy:
       matrix:
        os: [ubuntu-latest, ubuntu 20.0.4, windows-latest]
     runs-on: ${{matrix.os}}
     steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Images on ${{matrix.os}}
        run: docker run ${{matrix.images}}  